# MySQL Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testDB
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true